version: '3.8'
services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@db:5432/mydatabase"
    depends_on:
      - db
    networks:
      - app-network

  postgres:
    image: postgres:10.3
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
volumes:
  postgres: