services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      DATABASE_URL: "postgresql://postgres:password@db:5432/mydatabase"
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    container_name: moveit
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - '5433:5432'
    volumes:
      - ./.postgres-data:/var/lib/postgresql/data

volumes:
  .postgres-data: